imports:
    - { resource: "@BloggerUserBundle/Resources/config/security.yml" }

security:


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/add, role: ROLE_ADMIN }
        - { path: ^/edit, role: ROLE_ADMIN }
        - { path: ^/delete, role: ROLE_ADMIN }
