BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Default:index }


BloggerBlogBundle_add:
    path:  /add
    defaults: { _controller: BloggerBlogBundle:Default:add }
