BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Default:index }


BloggerBlogBundle_add:
    path:  /add
    defaults: { _controller: BloggerBlogBundle:Default:add }

BloggerBlogBundle_article:
    path:  /article/{id}
    defaults: { _controller: BloggerBlogBundle:Default:article }
    requirements:
        id: \d+